 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Abdelrahman Mohamed Farid
 ******************************************************************************/

#include "Port.h"
#include "Port_Types.h"

/* PB structure used with Dio_Init API */
const Port_ConfigType Port_Configurations = {
     /* PORTA */
     PORTA_ID, PIN_0, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_1, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_4, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_5, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_6, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTA_ID, PIN_7, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     /* PORTB */
     PORTB_ID, PIN_0, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO, 
     PORTB_ID, PIN_1, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_4, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_5, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_6, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_7, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     /* PORTC */
     PORTB_ID, PIN_0, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_1, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_4, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_5, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_6, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTB_ID, PIN_7, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     /* PORTD */
     PORTD_ID, PIN_0, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_1, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_4, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_5, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_6, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTD_ID, PIN_7, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     /* PORTE */
     PORTE_ID, PIN_0, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTE_ID, PIN_1, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTE_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTE_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTE_ID, PIN_4, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTE_ID, PIN_5, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     /* PORTF*/
     PORTF_ID, PIN_0, PORT_PIN_IN, PULL_UP, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,      /* Switch 1 */
     PORTF_ID, PIN_1, PORT_PIN_OUT, Port_OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,         /* Led */
     PORTF_ID, PIN_2, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTF_ID, PIN_3, PORT_PIN_IN, PULL_DOWN, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO,
     PORTF_ID, PIN_4, PORT_PIN_IN, PULL_UP, PORT_PIN_LEVEL_HIGH, PORT_PIN_MODE_DIO      /* Switch 2 */
};